[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all to Next.js handler
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
